### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by iovuio** [rixo/svench#22]
Following the instructions: clone, `cd example`, `yarn`, `yarn svench`
Got
> yarn svench
yarn run v1.22.10
warning package.json: No license field
$ rollup --config rollup.config.svench.js --watch
[!] TypeError: rollup.svenchify is not a function
TypeError: rollup.svenchify is not a function
    at Object.<anonymous> (C:\Users\whatever\temp\svench\example\rollup.config.svench.js:26:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.require.extensions.<computed> [as .js] (C:\Users\whatever\temp\svench\example\node_modules\rollup\dist\shared\loadConfigFile.js:516:20)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadConfigFromBundledFile (C:\Users\whatever\temp\svench\example\node_modules\rollup\dist\shared\loadConfigFile.js:524:42)
    at getDefaultFromTranspiledConfigFile (C:\Users\whatever\temp\svench\example\node_modules\rollup\dist\shared\loadConfigFile.js:509:12)
    at loadConfigFile (C:\Users\whatever\temp\svench\example\node_modules\rollup\dist\shared\loadConfigFile.js:487:15)

**Comment by dipscom** [comment]
Hi @iovuio!

Sorry about the silence for so long. Rixo's working on a new iteration of Svench that is consuming all his spare time.

The current documentation and examples are out of sync with the codebase at the moment. It will be adjusted when this update Rixo's working on rolls out.

For now I can try to help you get a project going if you are looking to experiment with Svench. Let me know what do you need.

ps: I don't actually contribute with code in this project, I'm only a user like yourself but I like it so much I'm trying to help out with support and documentation. My knowledge of the actual workings of it is very, very limited.

**Comment by iovuio** [comment]
@dipscom,
Thank you for the context info and offer to help.
Nothing urgent on my side. I will watch what's happening on master and try again later.
