### ISSUE TITLE
svench cli is throwing error from vite-plugin-svelte

### ISSUE THREAD

**Issue by bhvngt** [rixo/svench#35]
Trie running svench. Its throwing following error. Even after throwing the exception its working fine though.. 

Not sure if I am missing something with config or packaging?

```
11:03:47 PM [vite-plugin-svelte] failed to import config /Volumes/DATA/Bhavin/Projects/lab/innerview/libs/ui/svelte.config.js
TypeError: A dynamic import callback was not specified.
    at new NodeError (node:internal/errors:370:5)
    at exports.importModuleDynamicallyCallback (node:internal/process/esm_loader:34:9)
    at loadSvelteConfig (node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.14_svelte@3.40.1+vite@2.4.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:429:30)
    at resolveOptions (node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.14_svelte@3.40.1+vite@2.4.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:599:30)
    at Object.config (node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.14_svelte@3.40.1+vite@2.4.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:1039:23)
    at resolveConfig (node_modules/.pnpm/vite@2.4.3/node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:75052:33)
    at createServer (node_modules/.pnpm/vite@2.4.3/node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:73563:26)
    at default (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/commands/vite/dev.js:15:24)
    at async asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:138:5)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at exports.importModuleDynamicallyCallback (node:internal/process/esm_loader:25:57)
    at loadSvelteConfig (node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.14_svelte@3.40.1+vite@2.4.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:429:30)
    at resolveOptions (node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.14_svelte@3.40.1+vite@2.4.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:599:30)
    at Object.config (node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.14_svelte@3.40.1+vite@2.4.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs:1039:23)
    at resolveConfig (node_modules/.pnpm/vite@2.4.3/node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:75052:33)
    at createServer (node_modules/.pnpm/vite@2.4.3/node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:73563:26)
    at default (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/commands/vite/dev.js:15:24)
    at async asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:138:5)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at loadSvenchifiedConfig (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/commands/vite/util.js:49:38)
    at default (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/commands/vite/dev.js:9:29)
    at async asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:138:5)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at loadVite (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/commands/vite/util.js:39:25)
    at default (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/commands/vite/dev.js:7:34)
    at node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:101:10
    at async asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:138:5)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at ensureRuntimeFor (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:62:26)
    at node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:98:11
    at async asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:138:5)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at exports.importModuleDynamicallyCallback (node:internal/process/esm_loader:25:57)
    at node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:92:32
    at async asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:138:5)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at inspect (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/lib/inspect.js:68:24)
    at node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:79:22
    at asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:138:11)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:134:18)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at asyncAction (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:123:23)
    at node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:143:20
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at CAC.<anonymous> (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:143:8)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at CAC.<anonymous> (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:142:13)
    at CAC.runMatchedCommand (node_modules/.pnpm/cac@6.7.3/node_modules/cac/dist/index.mjs:607:34)
    at CAC.parse (node_modules/.pnpm/cac@6.7.3/node_modules/cac/dist/index.mjs:534:12)
    at default (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:239:8)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at PromiseWrap.emitInitNative (node:internal/async_hooks:203:43)
    at readPkg (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:54:17)
    at default (node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli/cli.js:112:21)
    at node_modules/.pnpm/svench@0.2.0-28_svelte@3.40.1+vite@2.4.3/node_modules/svench/cli.bin.js:47:1
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12) {
  c
```

Here's my package.json
```
"dependencies": {
    "svelte": "^3.40.1"
  },
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.14",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/svelte": "^3.0.3",
    "@types/jest": "^26.0.24",
    "@types/testing-library__jest-dom": "^5.14.1",
    "jest": "^27.0.6",
    "svelte-check": "^2.2.3",
    "svelte-jester": "^1.7.0",
    "svelte-preprocess": "^4.7.4",
    "svench": "^0.2.0-28",
    "ts-jest": "^27.0.4",
    "tslib": "^2.3.0",
    "typescript": "^4.3.5",
    "vite": "^2.4.3"
  },
```

**Comment by rixo** [comment]
Seems like it's trying to import an inexistant module...

Do you actually have something at `/Volumes/DATA/Bhavin/Projects/lab/innerview/libs/ui/svelte.config.js`?

What is there in this file?

Is your project using native ESM (`"type": "module"` in package.json)?

**Comment by bhvngt** [comment]
Yep Sorry. It wasn't native esm.

After I added `{type: "module"}` and remove `svelte.config.js`, the error disappeared. Would `svench` cli conflict with existing `svelte.config.js`?

**Comment by bhvngt** [comment]
I really appreciate this project. Simple, lightweight and performant then [storybook](https://storybook.js.org).
